### ISSUE TITLE
local build / sass-embedded (1.71.0) install problem on FreeBSD

### ISSUE THREAD

**Issue by cederom** [apache/nuttx-website#106]
Hey there @btashton :-)

I have problem building local preview of the website on FreeBSD 13.2 - cannot install `sass-embedded (1.71.0)`. Would it be possible to resolve / update version conflicts please? :-)

```
% uname -a
FreeBSD octagon 13.2-RELEASE-p10 FreeBSD 13.2-RELEASE-p10 GENERIC amd64
```

I am following instructions from README:

```
export GEM_HOME=$HOME/.gem # Adjust this path as you want
export PATH=$PATH:$GEM_HOME/bin
bundle exec jekyll serve
```

Result is:

```
% bundle exec jekyll serve
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Could not find jekyll-4.3.2 in any of the sources
Run `bundle install` to install missing gems.
```

then:

```
% bundle install
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Fetching gem metadata from https://rubygems.org/
Fetching gem metadata from https://rubygems.org/...........
Using rake 13.0.6
Using public_suffix 5.0.1
Using bundler 2.2.22
Using rb-fsevent 0.11.2
Using concurrent-ruby 1.2.2
Using rexml 3.2.5
Using mercenary 0.4.0
Using ffi 1.15.5
Using safe_yaml 1.0.5
Using google-protobuf 3.23.0
Using colorator 1.1.0
Using webrick 1.8.1
Using i18n 1.13.0
Using http_parser.rb 0.8.0
Using rouge 4.1.0
Using forwardable-extended 2.6.0
Using kramdown 2.4.0
Using rb-inotify 0.10.1
Using unicode-display_width 2.4.2
Using liquid 4.0.4
Using addressable 2.8.4
Using eventmachine 1.2.7
Using listen 3.8.0
Using em-websocket 0.5.3
Using kramdown-parser-gfm 1.1.0
Using terminal-table 3.0.2
Fetching sass-embedded 1.62.1
Using pathutil 0.16.2
Using jekyll-watch 2.2.1
Installing sass-embedded 1.62.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/gems/sass-embedded-1.62.1/ext/sass
/usr/local/bin/ruby31 -rrubygems /usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/gems/rake-13.1.0/exe/rake
RUBYARCHDIR\=/usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/extensions/amd64-freebsd-13/3.1/sass-embedded-1.62.1
RUBYLIBDIR\=/usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/extensions/amd64-freebsd-13/3.1/sass-embedded-1.62.1
rake aborted!
NotImplementedError: sass_embedded for x86_64-freebsd13 not available at
https://github.com/sass/dart-sass-embedded/releases/tag/1.62.1
/usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/gems/sass-embedded-1.62.1/ext/sass/Rakefile:249:in
`default_sass_embedded'
/usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/gems/sass-embedded-1.62.1/ext/sass/Rakefile:21:in `block (2
levels) in <top (required)>'
/usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/gems/sass-embedded-1.62.1/ext/sass/Rakefile:21:in `fetch'
/usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/gems/sass-embedded-1.62.1/ext/sass/Rakefile:21:in `block in <top
(required)>'
/usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/gems/rake-13.1.0/exe/rake:27:in `<main>'
Tasks: TOP => default => install => embedded.rb => sass_embedded
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/gems/sass-embedded-1.62.1 for
inspection.
Results logged to
/usr/home/cederom/.local/share/gem/ruby/3.1/ruby/3.1/extensions/amd64-freebsd-13/3.1/sass-embedded-1.62.1/gem_make.out

An error occurred while installing sass-embedded (1.62.1), and Bundler cannot continue.
Make sure that `gem install sass-embedded -v '1.62.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  jekyll-feed was resolved to 0.17.0, which depends on
    jekyll was resolved to 4.3.2, which depends on
      jekyll-sass-converter was resolved to 3.0.0, which depends on
        sass-embedded
```

**Comment by btashton** [comment]
```
NotImplementedError: sass_embedded for x86_64-freebsd13 not available at
https://github.com/sass/dart-sass-embedded/releases/tag/1.62.1
```
Looks like upstream does not support x86_64-freebsd13 not much I can do for you here.

**Comment by cederom** [comment]
Yup, it seems that `dart-sass-embedded` is abandoned and the code moved to the `sass`. This one seems to be available on FreeBSD:

```
% pkg search sass
R-cran-sass-0.4.8              Syntactically Awesome Style Sheets ('Sass')
clamassassin-1.2.4_7           Simple virus filter wrapper for ClamAV
claws-mail-spamassassin-3.19.1 SpamAssassin plugin for Claws Mail
libsass-3.6.6                  C/C++ implementation of a Sass compiler
p5-CSS-Sass-3.6.4              Compile .scss and .sass files using LibSass
p5-Plack-Middleware-File-Sass-0.03_1 Perl extension for Sass support for all Plack frameworks
p5-Text-Sass-0.97_2            Perl implementation of http://sass-lang.com/
py39-django-libsass-0.7        Filter to compile SASS files using libsass
py39-libsass-0.23.0            Straightforward binding of libsass for Python
rubygem-bootstrap-sass-3.4.1   Bootstrap by Twitter
rubygem-dartsass-1.49.8_1      RubyGem wrapper for the Dart Sass binary
rubygem-jekyll-sass-converter-2.2.0 Basic Sass converter for Jekyll
rubygem-jekyll-sass-converter1-1.5.2 Basic Sass converter for Jekyll
rubygem-sass-3.7.4             Sass is an extension of CSS3
rubygem-sass-listen-4.0.0      Listens to file modifications
rubygem-sass-rails-rails4-6.0.0 Sass adapter for the Rails asset pipeline
rubygem-sass-rails-rails5-6.0.0 Sass adapter for the Rails asset pipeline
rubygem-sass-rails-rails50-6.0.0 Sass adapter for the Rails asset pipeline
rubygem-sass-rails-rails52-6.0.0 Sass adapter for the Rails asset pipeline
rubygem-sass-rails-rails60-6.0.0 Sass adapter for the Rails asset pipeline
rubygem-sass-rails-rails61-6.0.0 Sass adapter for the Rails asset pipeline
rubygem-sass-rails-rails70-6.0.0 Sass adapter for the Rails asset pipeline
rubygem-sassc-2.4.0            Use libsass with Ruby
rubygem-sassc-rails-rails4-2.1.2_1 Integrate SassC-Ruby into Rails
rubygem-sassc-rails-rails5-2.1.2_1 Integrate SassC-Ruby into Rails
rubygem-sassc-rails-rails50-2.1.2_1 Integrate SassC-Ruby into Rails
rubygem-sassc-rails-rails52-2.1.2_1 Integrate SassC-Ruby into Rails
rubygem-sassc-rails-rails60-2.1.2_2 Integrate SassC-Ruby into Rails
rubygem-sassc-rails-rails61-2.1.2 Integrate SassC-Ruby into Rails
rubygem-sassc-rails-rails70-2.1.2 Integrate SassC-Ruby into Rails
rubygem-sassc22-2.2.1          Use libsass with Ruby
rubygem-semantic-ui-sass-2.2.12.1 Semantic UI, converted to Sass and ready to drop into Rails & Compass
rubygem-sprockets-sass-1.3.1_1 Implements a sprockets-aware sass importer
sassc-3.6.1                    Wrapper around libsass
spamassassin-4.0.0_6           Highly efficient mail filter for identifying spam
spamassassin-devel-2024.02.06_2 Highly efficient mail filter for identifying spam
spamassassin-dqs-1.5.1_1       Real-Time DNSBL's that catch a bunch of additional spam
octagon% pkg search dart
darts-0.32_1                   C++ template library that implements Double-Array
dartsim-6.13.0_4               Dynamic Animation and Robotics Toolkit
py39-darts.util.lru-0.5        Simple dictionary with LRU behaviour in Python
rubygem-dartsass-1.49.8_1      RubyGem wrapper for the Dart Sass binary
```

What is necessary to update our website? Is it enforced anyhow by Apache template or we can freely modify it? How can I help? :-)

**Comment by cederom** [comment]
Okay I can see the website needs a solid update in several places. If this is Apache template then we may simply update the template?

When installed system packages and not using local home environment jekyll started to build the website.. but there is a obsolete syntax inside: 

```
% bundle exec jekyll serve
Configuration file: /XXX/nuttx-website.git/_config.yml
            Source: /XXX/nuttx-website.git
       Destination: /XXX/nuttx-website.git/target
 Incremental build: disabled. Enable with --incremental
      Generating...
     Build Warning: Layout 'news_item' requested in _posts/2019-12-19-hello.md does not exist.
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    Error: Invalid CSS after "...ont-weight list": expected expression (e.g. 1px, bold), was ".slash($base-font-s" on line 19:33 of _sass/_base.scss from line 46:1 of main.scss >> font: $base-font-weight list.slash($base-font-size, $base-line-height) $ --------------------------------^
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:200:in `rescue in sass_convert': Error: Invalid CSS after "...ont-weight list": expected expression (e.g. 1px, bold), was ".slash($base-font-s" (Jekyll::Converters::Scss::SyntaxError)
        on line 19:33 of _sass/_base.scss
        from line 46:1 of main.scss
>>     font: $base-font-weight list.slash($base-font-size, $base-line-height) $
   --------------------------------^
        from /usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:192:in `sass_convert'
        from /usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:186:in `convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:105:in `block in convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `reduce'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:84:in `render_document'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:564:in `block in render_pages'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `render_pages'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:211:in `render'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:25:in `load'
        from /usr/local/bin/jekyll:25:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/exe/bundle:37:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/exe/bundle:29:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
/zraid/data/cederom/work/CeDeROM/lab/embedded/nuttx/nuttx-website.git/_sass/_base.scss:19: Error: Invalid CSS after "...ont-weight list": expected expression (e.g. 1px, bold), was ".slash($base-font-s" (SassC::SyntaxError)
        on line 19:33 of _sass/_base.scss
        from line 46:1 of main.scss
>>     font: $base-font-weight list.slash($base-font-size, $base-line-height) $
   --------------------------------^
        from /usr/local/lib/ruby/gems/3.1/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
        from /usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:195:in `sass_convert'
        from /usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:186:in `convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:105:in `block in convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `reduce'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:84:in `render_document'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:564:in `block in render_pages'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `render_pages'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:211:in `render'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:25:in `load'
        from /usr/local/bin/jekyll:25:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/exe/bundle:37:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/exe/bundle:29:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
```

Some remarks on removing `.slash()` here https://github.com/jekyll/minima/issues/709.
