### ISSUE TITLE
_sass/_base.scss: use of obsolete .slash() function.

### ISSUE THREAD

**Issue by cederom** [apache/nuttx-website#110]
While building the local preview of the website `jekyll serve` complains about invalid use of `.slash()` function. Some remarks on removing `.slash()` here https://github.com/jekyll/minima/issues/709.

Using:
* clean `Gemfile.lock`.
* `rubygem-jekyll-4.3.2_1` system package.
* `rubygem-jekyll-sass-converter-2.2.0` system package.
* `rubygem-jekyll-feed-0.17.0` system package.
* FreeBSD 13.2-RELEASE AMD64.

Detailed output below:

```
% bundle exec jekyll serve
Configuration file: /XXX/nuttx-website.git/_config.yml
            Source: /XXX/nuttx-website.git
       Destination: /XXX/nuttx-website.git/target
 Incremental build: disabled. Enable with --incremental
      Generating...
     Build Warning: Layout 'news_item' requested in _posts/2019-12-19-hello.md does not exist.
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    Error: Invalid CSS after "...ont-weight list": expected expression (e.g. 1px, bold), was ".slash($base-font-s" on line 19:33 of _sass/_base.scss from line 46:1 of main.scss >> font: $base-font-weight list.slash($base-font-size, $base-line-height) $ --------------------------------^
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:200:in `rescue in sass_convert': Error: Invalid CSS after "...ont-weight list": expected expression (e.g. 1px, bold), was ".slash($base-font-s" (Jekyll::Converters::Scss::SyntaxError)
        on line 19:33 of _sass/_base.scss
        from line 46:1 of main.scss
>>     font: $base-font-weight list.slash($base-font-size, $base-line-height) $
   --------------------------------^
        from /usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:192:in `sass_convert'
        from /usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:186:in `convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:105:in `block in convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `reduce'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:84:in `render_document'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:564:in `block in render_pages'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `render_pages'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:211:in `render'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:25:in `load'
        from /usr/local/bin/jekyll:25:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/exe/bundle:37:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/exe/bundle:29:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
/zraid/data/cederom/work/CeDeROM/lab/embedded/nuttx/nuttx-website.git/_sass/_base.scss:19: Error: Invalid CSS after "...ont-weight list": expected expression (e.g. 1px, bold), was ".slash($base-font-s" (SassC::SyntaxError)
        on line 19:33 of _sass/_base.scss
        from line 46:1 of main.scss
>>     font: $base-font-weight list.slash($base-font-size, $base-line-height) $
   --------------------------------^
        from /usr/local/lib/ruby/gems/3.1/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
        from /usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:195:in `sass_convert'
        from /usr/local/lib/ruby/gems/3.1/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:186:in `convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:105:in `block in convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `reduce'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `convert'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:84:in `render_document'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:564:in `block in render_pages'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `render_pages'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:211:in `render'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/home/cederom/.local/share/gem/ruby/3.1/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:25:in `load'
        from /usr/local/bin/jekyll:25:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/exe/bundle:37:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.1/gems/bundler-2.4.20/exe/bundle:29:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
```

**Comment by cederom** [comment]
I got into details of nuttx-website a bit and I am wondering if we really need to use RubyGems to create such a simple www. We could go simple static HTML website and that would remove dependencies and build problems completely.

**Comment by cederom** [comment]
Fixed with https://github.com/apache/nuttx-website/pull/151 :-)
